Add q3 roadmap
meilisearch/core-team pull request #6
Opened 2021-06-28 14:02 UTC by curquiza

2021-06-28 16:12 UTC, curquiza commented on roadmaps/2021.md
> +- [ ] CSV
```suggestion
- [ ] CSV
- [ ] Improve analytics
```

2021-06-29 09:22 UTC, gmourier requested changes
I just reorganized according to the goals of Q3 in order to bring some precisions 😇

2021-06-29 09:22 UTC, gmourier commented on roadmaps/2021.md
> +
```suggestion
### Goals

- Reduce biggest user's deal-breakers.
- Start to stabilize the API format block by block until v1.0. 
- Understand our user's behaviors.
- Patch v0.21 indexing speed.
```

2021-06-29 09:22 UTC, gmourier commented on roadmaps/2021.md
> +  - [ ] Indexes
```suggestion
- [ ] Indexation benchmarks (Patch v0.21 indexing speed)

### New features

#### Reduce biggest user's deal-breakers
- [ ] SortBy
- [ ] Geo search

#### Patch v0.21 indexing speed
- [ ] Indexing NDJSON file format
- [ ] Indexing CSV file format
- [ ] Indexer optimization

#### Understand our user's behaviors.
- [ ] Branch analytics at feature level (On those planned in this quarter)

#### Stabilize the API format block by block until v1.0.
- [ ] Clean API Format
  - [ ] Search
  - [ ] Documents
  - [ ] Updates
  - [ ] Indexes
```

2021-06-29 09:22 UTC, gmourier commented on roadmaps/2021.md
> +- [ ] Indexer
```suggestion
```

2021-06-29 10:51 UTC, gmourier commented on roadmaps/2021.md
> +- [ ] Indexer
I moved the optimization line under the objective of improving indexing performance! Thanks, your work @curquiza!

2021-06-29 14:01 UTC, gmourier approved these changes
LGTM 🥳

2021-06-29 14:31 UTC, tpayet approved these changes
🙌

2021-06-29 14:35 UTC, merged